/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Client.GUI.Component;

import Client.GUI.Lib.GlobalVariable;
import Client.GUI.Lib.RoundBorder;
import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author Admin
 */
public class OthersGUI extends javax.swing.JPanel {

    /**
     * Creates new form OtherGUI
     */
    public OthersGUI() {
        initComponents();
        //set jlable color
        this.LabelHeader.setForeground(GlobalVariable.primaryColor);
        //set border rounded
        setBorderRounded(this);
        //set hover
        setHover(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelHeader = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        wrapperInputTime = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        wrapperBtnView = new javax.swing.JPanel();
        btnView = new javax.swing.JLabel();
        wrapperBtnShutdown = new javax.swing.JPanel();
        btnShutdown = new javax.swing.JLabel();
        wrapperBtnLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        LabelHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelHeader.setText("Logger / Logout / Shutdown");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Keys and clipboard logger");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Interval send to server");

        jTextField1.setBorder(null);

        javax.swing.GroupLayout wrapperInputTimeLayout = new javax.swing.GroupLayout(wrapperInputTime);
        wrapperInputTime.setLayout(wrapperInputTimeLayout);
        wrapperInputTimeLayout.setHorizontalGroup(
            wrapperInputTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperInputTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addContainerGap())
        );
        wrapperInputTimeLayout.setVerticalGroup(
            wrapperInputTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperInputTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        wrapperBtnView.setOpaque(false);

        btnView.setBackground(new java.awt.Color(46, 79, 79));
        btnView.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnView.setText("View");
        btnView.setOpaque(true);
        btnView.setPreferredSize(new java.awt.Dimension(74, 20));

        javax.swing.GroupLayout wrapperBtnViewLayout = new javax.swing.GroupLayout(wrapperBtnView);
        wrapperBtnView.setLayout(wrapperBtnViewLayout);
        wrapperBtnViewLayout.setHorizontalGroup(
            wrapperBtnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wrapperBtnViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        wrapperBtnViewLayout.setVerticalGroup(
            wrapperBtnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wrapperBtnViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(wrapperBtnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(wrapperInputTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(73, 73, 73))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wrapperInputTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wrapperBtnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        wrapperBtnShutdown.setOpaque(false);

        btnShutdown.setBackground(new java.awt.Color(46, 79, 79));
        btnShutdown.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnShutdown.setForeground(new java.awt.Color(255, 255, 255));
        btnShutdown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnShutdown.setText("Shutdown");
        btnShutdown.setOpaque(true);
        btnShutdown.setPreferredSize(new java.awt.Dimension(74, 20));

        javax.swing.GroupLayout wrapperBtnShutdownLayout = new javax.swing.GroupLayout(wrapperBtnShutdown);
        wrapperBtnShutdown.setLayout(wrapperBtnShutdownLayout);
        wrapperBtnShutdownLayout.setHorizontalGroup(
            wrapperBtnShutdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
            .addGroup(wrapperBtnShutdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(wrapperBtnShutdownLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnShutdown, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        wrapperBtnShutdownLayout.setVerticalGroup(
            wrapperBtnShutdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
            .addGroup(wrapperBtnShutdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(wrapperBtnShutdownLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnShutdown, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        wrapperBtnLogout.setOpaque(false);

        btnLogout.setBackground(new java.awt.Color(46, 79, 79));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogout.setText("Logout");
        btnLogout.setOpaque(true);
        btnLogout.setPreferredSize(new java.awt.Dimension(74, 20));

        javax.swing.GroupLayout wrapperBtnLogoutLayout = new javax.swing.GroupLayout(wrapperBtnLogout);
        wrapperBtnLogout.setLayout(wrapperBtnLogoutLayout);
        wrapperBtnLogoutLayout.setHorizontalGroup(
            wrapperBtnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wrapperBtnLogoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        wrapperBtnLogoutLayout.setVerticalGroup(
            wrapperBtnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wrapperBtnLogoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wrapperBtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wrapperBtnShutdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wrapperBtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wrapperBtnShutdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(105, 105, 105))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelHeader;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnShutdown;
    private javax.swing.JLabel btnView;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel wrapperBtnLogout;
    private javax.swing.JPanel wrapperBtnShutdown;
    private javax.swing.JPanel wrapperBtnView;
    private javax.swing.JPanel wrapperInputTime;
    // End of variables declaration//GEN-END:variables

    private void setBorderRounded(OthersGUI aThis) {
        aThis.wrapperBtnView.setBorder(new RoundBorder(6, GlobalVariable.primaryColor));

        aThis.wrapperBtnShutdown.setBorder(new RoundBorder(6, GlobalVariable.WarningColor));
        aThis.btnShutdown.setBackground(GlobalVariable.WarningColor);

        aThis.wrapperBtnLogout.setBorder(new RoundBorder(6, GlobalVariable.primaryColor));
        aThis.btnLogout.setBackground(GlobalVariable.primaryColor);

        aThis.wrapperInputTime.setBorder(new RoundBorder(6, Color.white));
    }

    private void setHover(OthersGUI aThis) {
        aThis.wrapperBtnView.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                //request pick client
                aThis.wrapperBtnView.setCursor(new Cursor(Cursor.HAND_CURSOR));

            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aThis.wrapperBtnView.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        });
        
       aThis.wrapperBtnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                //request pick client
                aThis.wrapperBtnLogout.setCursor(new Cursor(Cursor.HAND_CURSOR));

            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aThis.wrapperBtnLogout.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        });
       
       
       aThis.wrapperBtnShutdown.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                //request pick client
                aThis.wrapperBtnShutdown.setCursor(new Cursor(Cursor.HAND_CURSOR));

            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aThis.wrapperBtnShutdown.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        });
        
    }
}
