/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Client.GUI.Component;

import Client.GUI.Lib.GlobalVariable;
import Client.GUI.Lib.RoundBorder;
import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author Admin
 */
public class StreamingGUI extends javax.swing.JPanel {

    /**
     * Creates new form StreamingGUI
     */
    public StreamingGUI() {
        initComponents();
        //set jlable color
        this.LabelHeader.setForeground(GlobalVariable.primaryColor);
        //set border rounded
        setBorderRounded(this);
        //set hover
        setHover(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelHeader = new javax.swing.JLabel();
        panelStream = new javax.swing.JPanel();
        panelPicture = new javax.swing.JPanel();
        wrapperBtnSave = new javax.swing.JPanel();
        btnSave = new javax.swing.JLabel();
        warpperBtnCapture = new javax.swing.JPanel();
        btnCapture = new javax.swing.JLabel();
        wrapperBtnCancel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        LabelHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelHeader.setText("Streaming");

        panelStream.setOpaque(false);

        javax.swing.GroupLayout panelStreamLayout = new javax.swing.GroupLayout(panelStream);
        panelStream.setLayout(panelStreamLayout);
        panelStreamLayout.setHorizontalGroup(
            panelStreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelStreamLayout.setVerticalGroup(
            panelStreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        panelPicture.setOpaque(false);

        javax.swing.GroupLayout panelPictureLayout = new javax.swing.GroupLayout(panelPicture);
        panelPicture.setLayout(panelPictureLayout);
        panelPictureLayout.setHorizontalGroup(
            panelPictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelPictureLayout.setVerticalGroup(
            panelPictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        wrapperBtnSave.setOpaque(false);

        btnSave.setBackground(new java.awt.Color(46, 79, 79));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSave.setText("Save");
        btnSave.setOpaque(true);

        javax.swing.GroupLayout wrapperBtnSaveLayout = new javax.swing.GroupLayout(wrapperBtnSave);
        wrapperBtnSave.setLayout(wrapperBtnSaveLayout);
        wrapperBtnSaveLayout.setHorizontalGroup(
            wrapperBtnSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperBtnSaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        wrapperBtnSaveLayout.setVerticalGroup(
            wrapperBtnSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wrapperBtnSaveLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        warpperBtnCapture.setOpaque(false);

        btnCapture.setBackground(new java.awt.Color(46, 79, 79));
        btnCapture.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCapture.setForeground(new java.awt.Color(255, 255, 255));
        btnCapture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCapture.setText("Capture");
        btnCapture.setOpaque(true);
        btnCapture.setPreferredSize(new java.awt.Dimension(74, 20));

        javax.swing.GroupLayout warpperBtnCaptureLayout = new javax.swing.GroupLayout(warpperBtnCapture);
        warpperBtnCapture.setLayout(warpperBtnCaptureLayout);
        warpperBtnCaptureLayout.setHorizontalGroup(
            warpperBtnCaptureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warpperBtnCaptureLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCapture, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        warpperBtnCaptureLayout.setVerticalGroup(
            warpperBtnCaptureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warpperBtnCaptureLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCapture, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        wrapperBtnCancel.setOpaque(false);

        btnCancel.setBackground(new java.awt.Color(46, 79, 79));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancel.setText("Cancel");
        btnCancel.setOpaque(true);

        javax.swing.GroupLayout wrapperBtnCancelLayout = new javax.swing.GroupLayout(wrapperBtnCancel);
        wrapperBtnCancel.setLayout(wrapperBtnCancelLayout);
        wrapperBtnCancelLayout.setHorizontalGroup(
            wrapperBtnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperBtnCancelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );
        wrapperBtnCancelLayout.setVerticalGroup(
            wrapperBtnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wrapperBtnCancelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                                .addComponent(wrapperBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(wrapperBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(warpperBtnCapture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(panelPicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelStream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelStream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(warpperBtnCapture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 153, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wrapperBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wrapperBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelHeader;
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnCapture;
    private javax.swing.JLabel btnSave;
    private javax.swing.JPanel panelPicture;
    private javax.swing.JPanel panelStream;
    private javax.swing.JPanel warpperBtnCapture;
    private javax.swing.JPanel wrapperBtnCancel;
    private javax.swing.JPanel wrapperBtnSave;
    // End of variables declaration//GEN-END:variables

    private void setBorderRounded(StreamingGUI aThis) {
        aThis.wrapperBtnCancel.setBorder(new RoundBorder(6, Color.BLACK));
        aThis.btnCancel.setBackground(Color.BLACK);

        aThis.wrapperBtnSave.setBorder(new RoundBorder(6, Color.BLUE));
        aThis.btnSave.setBackground(Color.BLUE);

        aThis.warpperBtnCapture.setBorder(new RoundBorder(6, GlobalVariable.primaryColor));

        aThis.panelPicture.setBorder(new RoundBorder(6, Color.GRAY));
        aThis.panelStream.setBorder(new RoundBorder(6, Color.gray));
    }

    private void setHover(StreamingGUI aThis) {
        aThis.wrapperBtnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                //request pick client
                aThis.wrapperBtnCancel.setCursor(new Cursor(Cursor.HAND_CURSOR));

            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aThis.wrapperBtnCancel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        });
        
        
        aThis.warpperBtnCapture.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                //request pick client
                aThis.warpperBtnCapture.setCursor(new Cursor(Cursor.HAND_CURSOR));

            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aThis.warpperBtnCapture.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        });
        
        
        aThis.wrapperBtnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                //request pick client
                aThis.wrapperBtnSave.setCursor(new Cursor(Cursor.HAND_CURSOR));

            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aThis.wrapperBtnSave.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        });
    }
}
